import { mkdir, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { ApiDescription, ApiDtoProperty, ApiRoute } from '../agent';

function capitalize(s: string) { return s.charAt(0).toUpperCase() + s.slice(1); }

function mapGqlType(type: string, required = true): string {
  let base: string;
  if (type.includes('number') || type === 'int') base = 'Int';
  else if (type.includes('boolean')) base = 'Boolean';
  else if (type.includes('[]') || type === 'array') base = '[String!]';
  else base = 'String';
  return required ? `${base}!` : base;
}

async function write(filePath: string, content: string) {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf8');
}

function buildInputTypes(description: ApiDescription): string {
  const seen = new Set<string>();
  const types: string[] = [];

  function buildInput(name: string, props: ApiDtoProperty[]) {
    if (seen.has(name)) return;
    seen.add(name);

    for (const p of props) {
      if (p.properties?.length) buildInput(`${name}${capitalize(p.name)}Input`, p.properties);
    }

    const fields = props.map(p => {
      if (p.properties?.length) {
        const nested = `${name}${capitalize(p.name)}Input`;
        return `  ${p.name}: ${p.required ? `${nested}!` : nested}`;
      }
      return `  ${p.name}: ${mapGqlType(p.type || 'string', p.required !== false)}`;
    });

    types.push(`input ${name} {\n${fields.join('\n')}\n}`);
  }

  for (const route of description.routes) {
    if (route.requestDto) buildInput(route.requestDto.name, route.requestDto.properties);
  }

  return types.join('\n\n');
}

function buildSchema(description: ApiDescription): string {
  const entityName = capitalize(description.featureName);

  const responseFields = `  id: ID!\n  name: String!\n  email: String`;
  const inputTypes = buildInputTypes(description);

  const queries = description.routes
    .filter(r => r.method === 'get')
    .map(route => {
      const hasPathParam = /:(\w+)/.test(route.path);
      const paramName = route.path.match(/:(\w+)/)?.[1] ?? 'id';
      const isList = (route.responseType ?? '').includes('[]');
      const returnType = isList ? `[${entityName}!]!` : `${entityName}`;
      const args = hasPathParam ? `(${paramName}: ID!)` : '';
      return `  ${route.actionName}${args}: ${returnType}`;
    })
    .join('\n');

  const mutations = description.routes
    .filter(r => r.method !== 'get')
    .map(route => {
      const input = route.requestDto ? `(input: ${route.requestDto.name}!)` : '';
      const isList = (route.responseType ?? '').includes('[]');
      const returnType = isList ? `[${entityName}!]!` : `${entityName}!`;
      return `  ${route.actionName}${input}: ${returnType}`;
    })
    .join('\n');

  return `# ${description.featureName} GraphQL Schema
# Generated by api-generator — add business logic in the resolver

type ${entityName} {
${responseFields}
}

${inputTypes}

type Query {
${queries || `  ${description.featureName}s: [${entityName}!]!`}
}

${mutations ? `type Mutation {\n${mutations}\n}` : ''}
`;
}

function buildObjectType(description: ApiDescription): string {
  const entityName = capitalize(description.featureName);
  return `import { ObjectType, Field, ID } from '@nestjs/graphql';

@ObjectType()
export class ${entityName} {
  @Field(() => ID)
  id: string;

  @Field()
  name: string;

  @Field({ nullable: true })
  email?: string;
}
`;
}

function buildInputDecorators(description: ApiDescription): string {
  const seen = new Set<string>();
  const classes: string[] = [];

  function buildClass(name: string, props: ApiDtoProperty[]) {
    if (seen.has(name)) return;
    seen.add(name);

    for (const p of props) {
      if (p.properties?.length) buildClass(`${name}${capitalize(p.name)}Input`, p.properties);
    }

    const fields = props.map(p => {
      if (p.properties?.length) {
        const nested = `${name}${capitalize(p.name)}Input`;
        return p.required
          ? `  @Field(() => ${nested})\n  ${p.name}: ${nested};`
          : `  @Field(() => ${nested}, { nullable: true })\n  ${p.name}?: ${nested};`;
      }
      const tsType = (p.type || 'string').includes('number') ? 'number' : (p.type || 'string').includes('boolean') ? 'boolean' : 'string';
      const gqlType = tsType === 'number' ? 'Int' : tsType === 'boolean' ? 'Boolean' : 'String';
      return p.required
        ? `  @Field(() => ${gqlType})\n  ${p.name}: ${tsType};`
        : `  @Field(() => ${gqlType}, { nullable: true })\n  ${p.name}?: ${tsType};`;
    });

    classes.push(`@InputType()\nexport class ${name} {\n${fields.join('\n\n')}\n}`);
  }

  for (const route of description.routes) {
    if (route.requestDto) buildClass(route.requestDto.name, route.requestDto.properties);
  }

  return classes.join('\n\n');
}

function buildResolver(description: ApiDescription): string {
  const entityName = capitalize(description.featureName);
  const dtoNames = [...new Set(description.routes.filter(r => r.requestDto).map(r => r.requestDto!.name))];

  const queries = description.routes.filter(r => r.method === 'get').map(route => {
    const hasPathParam = /:(\w+)/.test(route.path);
    const paramName = route.path.match(/:(\w+)/)?.[1] ?? 'id';
    const isList = (route.responseType ?? '').includes('[]');
    const returnGqlType = isList ? `[${entityName}]` : entityName;
    const args = hasPathParam ? `@Args('${paramName}') ${paramName}: string` : '';
    const jsdoc = [
      hasPathParam ? ` * @param ${paramName} - Identifier to query` : '',
      ` * @returns ${isList ? `Array of ${entityName}` : entityName}`,
    ].filter(Boolean).join('\n');
    return `  /**
   * ${route.summary || route.actionName}
   *
${jsdoc}
   */
  @Query(() => ${returnGqlType}, { nullable: true })
  async ${route.actionName}(${args}) {
    // TODO: replace with actual business logic
    return { id: '1', name: 'Sample ${entityName}', email: 'sample@example.com' };
  }`;
  }).join('\n\n');

  const mutations = description.routes.filter(r => r.method !== 'get').map(route => {
    const input = route.requestDto ? `@Args('input') input: ${route.requestDto.name}` : '';
    const jsdoc = route.requestDto
      ? ` * @param input - ${route.requestDto.name} mutation payload\n * @returns mutated ${entityName}`
      : ` * @returns ${entityName}`;
    return `  /**
   * ${route.summary || route.actionName}
   *
   ${jsdoc}
   */
  @Mutation(() => ${entityName})
  async ${route.actionName}(${input}) {
    // TODO: replace with actual business logic
    return { id: '1', name: 'Sample ${entityName}', email: 'sample@example.com' };
  }`;
  }).join('\n\n');

  const inputImports = dtoNames.length ? `import { ${dtoNames.join(', ')} } from './${description.featureName}.input';` : '';
  const inputClasses = buildInputDecorators(description);

  return `import { Resolver, Query, Mutation, Args, Int } from '@nestjs/graphql';
import { ${entityName} } from './${description.featureName}.model';
${inputImports}

${inputClasses}

/**
 * GraphQL Resolver for the ${entityName} type.
 * Queries and Mutations are auto-exposed via the GraphQL Playground at /graphql.
 */
@Resolver(() => ${entityName})
export class ${entityName}Resolver {

${queries}

${mutations}
}
`;
}

function buildVendorService(description: ApiDescription): string {
  const cap = capitalize(description.featureName);
  const vendorRoutes = description.routes.filter(r => r.vendor);

  const methods = vendorRoutes.length > 0
    ? vendorRoutes.map(route => {
        const v = route.vendor!;
        const httpMethod = (v.method ?? route.method).toUpperCase();
        const hasPathParam = /:(\w+)/.test(route.path);
        const paramName = route.path.match(/:(\w+)/)?.[1] ?? 'id';
        const params = [
          hasPathParam ? `${paramName}: string` : '',
          route.requestDto ? `body?: Record<string, unknown>` : '',
        ].filter(Boolean).join(', ');
        const urlExpr = v.url.replace(/:(\w+)/g, (_: string, k: string) => `\${${k}}`);
        return `  async ${route.actionName}(${params}): Promise<unknown> {
    if (process.env.VENDOR_MOCK === 'true') {
      return { mocked: true, action: '${route.actionName}' };
    }
    const response = await fetch(\`${urlExpr}\`, {
      method: '${httpMethod}',
      headers: ${JSON.stringify(v.headers ?? { 'Content-Type': 'application/json' })},
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!response.ok) throw new Error(\`Vendor error \${response.status}\`);
    return response.json();
  }`;
      }).join('\n\n')
    : `  async fetchExternal(url: string, body?: unknown): Promise<unknown> {
    if (process.env.VENDOR_MOCK === 'true') {
      return { mocked: true };
    }
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!response.ok) throw new Error(\`Vendor error \${response.status}\`);
    return response.json();
  }`;

  return `import { Injectable } from '@nestjs/common';

@Injectable()
export class ${cap}VendorService {
${methods}
}
`;
}

function buildResolverSpec(description: ApiDescription): string {
  const cap = capitalize(description.featureName);
  const resolverClass = cap + 'Resolver';
  const vitestImport = description.testFramework === 'vitest'
    ? `import { describe, it, expect, beforeEach } from 'vitest';\n`
    : '';

  const tests = description.routes.map(route => {
    const hasPathParam = /:(\w+)/.test(route.path);
    const args = [
      hasPathParam ? `'1'` : '',
      route.requestDto
        ? `{ ${route.requestDto.properties.map(p => `${p.name}: '${p.name}-test'`).join(', ')} }`
        : '',
    ].filter(Boolean).join(', ');

    return `  it('should ${route.actionName}', async () => {
    const result = await resolver.${route.actionName}(${args});
    expect(result).toBeDefined();
  });`;
  }).join('\n\n');

  return `${vitestImport}import { Test, TestingModule } from '@nestjs/testing';
import { ${resolverClass} } from './${description.featureName}.resolver';

describe('${resolverClass}', () => {
  let resolver: ${resolverClass};

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [${resolverClass}],
    }).compile();
    resolver = module.get<${resolverClass}>(${resolverClass});
  });

${tests}
});
`;
}

export async function createGraphQLFiles(description: ApiDescription, rootDir: string) {
  const base = join(rootDir, description.baseRoute);

  await write(join(base, `${description.featureName}.schema.graphql`), buildSchema(description));
  await write(join(base, `${description.featureName}.resolver.ts`), buildResolver(description));
  await write(join(base, `${description.featureName}.model.ts`), buildObjectType(description));
  await write(join(base, `${description.featureName}.vendor.service.ts`), buildVendorService(description));
  await write(join(base, `${description.featureName}.resolver.spec.ts`), buildResolverSpec(description));

  console.log(`✓ [GraphQL] Generated for '${description.featureName}' → ${base}`);
}
